const {Pool} = require("pg");

const Client = new Pool({
   database: 'simplestore',
   port: 5432,
   user: 'postgres',
   password: '1111',
})

async function checkBaseVal(name){
    const client = await Client.connect();
    try{
        console.log("Connection successed");
        if (name === "users"){
          checkUsTable(name);
        } else if (name === "products") {
          checkProdTable(name);
        }
    }catch(err){
        console.log(err);
        throw new Error("Connection failed");
    }finally{
        client.release();
        console.log("Connection released");
    }
}

async function checkUsTable(name){
    const query = `
    CREATE TABLE IF NOT EXISTS ${name} (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name VARCHAR(100),
      email VARCHAR(100) UNIQUE,
      password VARCHAR(255),
      role VARCHAR(50) DEFAULT 'user'
    );
  `;
  const client  = await Client.connect();
  try {
    const a = await client.query(query);
  } catch (err) {
    console.error('Error: ', err);
    console.log("Table creation failed");
  }finally {
    client.release();
    console.log("Connection released");
  }
}

async function checkProdTable(name){
    const query = `
    CREATE TABLE IF NOT EXISTS ${name} (
      id SERIAL PRIMARY KEY,
      name VARCHAR(100) UNIQUE,
      price integer,
      color VARCHAR(50)
    );
  `;
  const client  = await Client.connect();

  try {
    await client.query(query);
    console.log("correct table");
  } catch (err) {
    console.error('Error: ', err);
    console.log("Table creation failed");
  }finally {
    client.release();
    console.log("Connection released");
  }
}

module.exports = checkBaseVal;